# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aandWnLuNqOcmr__Ut6mibE2W_ACYfJI
"""

from IPython.display import Image
display(Image(url='PASTE_IMAGE_URL_HERE'))

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load image (grayscale)
img = cv2.imread('alias.jpg', cv2.IMREAD_GRAYSCALE)

# Step 1: Simulate aliasing by downsampling
downsampled = img[::4, ::4]  # severe undersampling

# Step 2: Resize back (this shows aliasing artifacts)
aliased = cv2.resize(downsampled, (img.shape[1], img.shape[0]), interpolation=cv2.INTER_NEAREST)

# -----------------------------
# FIX: Anti-aliasing approach
# -----------------------------

# Step 3: Apply Gaussian blur BEFORE downsampling
blurred = cv2.GaussianBlur(img, (5, 5), 0)

# Step 4: Downsample after filtering
downsampled_fixed = blurred[::4, ::4]

# Step 5: Resize back using better interpolation
corrected = cv2.resize(downsampled_fixed, (img.shape[1], img.shape[0]), interpolation=cv2.INTER_CUBIC)

# -----------------------------
# Display results
# -----------------------------
plt.figure(figsize=(10, 6))

plt.subplot(1, 3, 1)
plt.title("Original")
plt.imshow(img, cmap='gray')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.title("Aliased Image")
plt.imshow(aliased, cmap='gray')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.title("Corrected (Anti-Aliased)")
plt.imshow(corrected, cmap='gray')
plt.axis('off')

plt.tight_layout()
plt.show()

